### ISSUE TITLE
Python3.9 AttributeError: 'array.array' object has no attribute 'fromstring'

### ISSUE THREAD

**Issue by utkutopcuoglu** [thruston/grid-banger#7] opened 2021-09-09 08:36 UTC
Python3.9 array module does not have `fromstring` method. Hence, you can't import osgb.

```
array.fromstring()
Deprecated alias for frombytes().

Deprecated since version 3.2, will be removed in version 3.9.
```

fromstring -> frombytes() seems to fix the problem

**Comment by thruston** [comment] 2021-09-09 08:57
Can you give me some more details about how you are trying to import osgb?   I do not see this error in my testing on 3.9.

I am aware that there is no "fromstring()" in python3's array, but if you look at the code carefully you will see that the section with "fromstring" is only used by python2.   Since python2.7 is still widely used in GIS I want to maintain backward compatibility for some months longer.

**Comment by utkutopcuoglu** [comment] 2021-09-09 08:58
Let me check it further for now, sorry if I made a mistake.

**Comment by thruston** [comment] 2021-09-09 09:00
You can see the test logs here, as they are all done by actions now.

https://github.com/thruston/grid-banger/runs/3415259823?check_suite_focus=true

**Comment by utkutopcuoglu** [comment] 2021-09-10 03:13
On 3.9.5 I see the following error:

```python3
Python 3.9.5 (default, May 11 2021, 08:20:37) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import  osgb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.9/site-packages/osgb/__init__.py", line 1, in <module>
    from osgb.convert import grid_to_ll, ll_to_grid
  File "/home/ubuntu/.local/lib/python3.9/site-packages/osgb/convert.py", line 36, in <module>
    OSTN_EE_SHIFTS.fromstring(pkgutil.get_data("osgb", "ostn_east_shift_82140"))
AttributeError: 'array.array' object has no attribute 'fromstring'
```
I can see that the current repo is correct [here](https://github.com/thruston/grid-banger/blob/55b1ea9953890b237cb91ee230be2dc7be4bbd72/osgb/convert.py#L32).

I am on ubuntu 21.04 and when I install osgb I get the following wrong code on site-packages:
```
OSTN_EE_SHIFTS = array.array(type_code)
OSTN_EE_SHIFTS.fromstring(pkgutil.get_data("osgb", "ostn_east_shift_82140"))
OSTN_EE_BASE = 82140

OSTN_NN_SHIFTS = array.array(type_code)
OSTN_NN_SHIFTS.fromstring(pkgutil.get_data("osgb", "ostn_north_shift_-84180"))
OSTN_NN_BASE = -84180
```
I am not sure why.

**Comment by lvphj** [comment] 2022-06-08 03:30
I'm having the same issue having used pip to install OSGB into a Conda environment on Windows with Python 3.9.12. The section of convert.py installed in site_packages\osgb is:

```
# OSTN data
if sys.version_info > (3,0):
    type_code = 'H'
else:
    type_code = b'H'

OSTN_EE_SHIFTS = array.array(type_code)
OSTN_EE_SHIFTS.from string(pkgutil.get_data("osgb","stn_east_shift_82140"))
OSTN_EE_B/ase = 82140

```
This differs from the content of convert.py shown on GitHub.

**Comment by thruston** [comment] 2022-06-08 09:06
Thanks for the report -- I may need a little time to investigate, as I do not have a Conda/Windows set up immediately to hand.

**Comment by thruston** [comment] 2022-06-08 09:15
It appears that the PyPI version is out of date -- I shall update it shortly.

**Comment by thruston** [comment] 2022-06-08 10:56
I have pushed v 1.1.0 to PyPI which contains the fix for this issue -- https://pypi.org/project/osgb/#history

@lvphj @utkutopcuoglu  you might like to try `pip3 install --upgrade osgb` 

I would be grateful for any feedback.

**Closed as completed by thruston** 2022-06-08 10:56 UTC

**Comment by lvphj** [comment] 2022-06-10 07:47
Thanks for the quick resolution of this issue - very much appreciated! I have tried several packages to convert grid references but osgb is the best I've found. Very glad to have it back.

I can confirm that I can now install osgb using pip on a Windows 10 machine without any issues and that I can import the osgb library without any errors.

Thanks again

**Comment by thruston** [comment] 2022-06-10 08:40
Thanks for the feedback.  Toby
